<iframe
  width="600"
  height="450"
  style="border:0"
  loading="lazy"
  allowfullscreen
  referrerpolicy="no-referrer-when-downgrade"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDPny6dN9B3rJv93XQIYh3lY4DDlGC7boU
    &q=Kidz+Korner+Milton">
</iframe>